config/routes.rb
Rails.application.routes.draw do
  root 'loans#landing_page'
  resources :loans
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/loan.rb
class Loan < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
  before_action :set_loan, only: %i[ show edit update destroy ]

  # GET /loans or /loans.json
  def index
    @loans = Loan.all
  end

  # GET /loans/1 or /loans/1.json
  def show
  end

  # GET /loans/new
  def new
    @loan = Loan.new
  end

  # GET /loans/1/edit
  def edit
  end

  # POST /loans or /loans.json
  def create
    @loan = Loan.new(loan_params)

    respond_to do |format|
      if @loan.save
        format.html { redirect_to @loan, notice: "Loan was successfully created." }
        format.json { render :show, status: :created, location: @loan }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @loan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /loans/1 or /loans/1.json
  def update
    respond_to do |format|
      if @loan.update(loan_params)
        format.html { redirect_to @loan, notice: "Loan was successfully updated." }
        format.json { render :show, status: :ok, location: @loan }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @loan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /loans/1 or /loans/1.json
  def landing_page
  end

  # DELETE /loans/1 or /loans/1.json
  def destroy
    @loan.destroy
    respond_to do |format|
      format.html { redirect_to loans_url, notice: "Loan was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_loan
      @loan = Loan.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def loan_params
      params.require(:loan).permit(:rating, :intent, :amount, :apr, :incubation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/loans_helper.rb
module LoansHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myapp</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <!-- Warning !! ensure that "stylesheet_pack_tag" is used, line below -->
  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<%= yield %>
</body>
</html>

app/views/loans/_form.html.erb
<!-- Stack the columns on mobile by making one full-width and the other half-width -->
<div class="main-content">
  <div class="container mt-7">
    <%= form_with(model: loan) do |f| %>
      <div class="card">
        <div class="card-body">

          <% if loan.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(loan.errors.count, "error") %> prohibited this loan from being saved:</h2>

              <ul>
                <% loan.errors.each do |error| %>
                  <li><%= error.full_message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <div class="mb-3">
            <%= f.label :rating, { class: "form-label" } %>
            <%= f.text_field :rating, { class: "form-control", placeholder: "Rating" } %>
          </div>

          <div class="mb-3">
            <%= f.label :intent, { class: "form-label" } %>
            <%= f.text_field :intent, { class: "form-control", placeholder: "Intent" } %>
          </div>

          <div class="mb-3">
            <%= f.label :amount, { class: "form-label" } %>
            <%= f.text_field :amount, { class: "form-control", placeholder: "Amount" } %>
          </div>

          <div class="mb-3">
            <%= f.label :apr, { class: "form-label" } %>
            <%= f.text_field :apr, { class: "form-control", placeholder: "Apr" } %>
          </div>

          <div class="mb-3">
            <%= f.label :incubation, { class: "form-label" } %>
            <%= f.text_field :incubation, { class: "form-control", placeholder: "Incubation" } %>
          </div>

          <%= f.submit "Submit", class: "btn btn-primary" %>

        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/loans/edit.html.erb
<h1>Editing Loan</h1>

<%= render 'form', loan: @loan %>

<%= link_to 'Show', @loan %> |
<%= link_to 'Back', loans_path %>

app/views/loans/new.html.erb
<h1>New Loan</h1>

<%= render 'form', loan: @loan %>

<%= link_to 'Back', loans_path %>

app/views/loans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rating:</strong>
  <%= @loan.rating %>
</p>

<p>
  <strong>Intent:</strong>
  <%= @loan.intent %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @loan.amount %>
</p>

<p>
  <strong>Apr:</strong>
  <%= @loan.apr %>
</p>

<p>
  <strong>Incubation:</strong>
  <%= @loan.incubation %>
</p>

<%= link_to 'Edit', edit_loan_path(@loan) %> |
<%= link_to 'Back', loans_path %>